# Generated by Django 4.2.4 on 2023-08-05 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
