# Generated by Django 4.2.4 on 2023-08-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
